## githubiverse-template by Gary Hodgson
## license: GPL3
##
## The data below is left as an example.  Please change each entry to match your requirements. 
## 

## Uses distinct namespace. Jekyll settings should go at the root level.
githubiverse:
    ## Metadata
    title: "Marcha Technology"
    author: L Chavalet
    license: GPL3
    tags: [Cubo mecanico, fun]

    ## Github project parameters.
    github:
        base: https://github.com/
        user: MarchaTechnology
        repository: Arte
        branch: master

    ## The names of directories where any images, source and stl files associated with the project can be found.
    img_dir: img
    stl_dir: Cube Gears
    src_dir: src

    ## The headline image
    lead_image: test-jig.jpg
    show_lead_image: true

    ## Optional. When uncommented appends the content of the file defined here to the project description.  Any text in index.md, after the yaml header, will be shown first.
    description_file: README.md

    ## Preview the first STL in the list when the page loads.
    autoload_stl: false

    ## Show a github "fork me" ribbon in the top righthand corner of the page.
    show_forkme_ribbon: true
